### ISSUE TITLE
No feedback on the exclusive bit mask after room gets filled and connected.

### ISSUE THREAD

**Issue by stolk** [playgameservices/android-basic-samples#161]
By using...
```
Builder& gpg::RealTimeRoomConfig::Builder::SetExclusiveBitMask	(	uint64_t 	exclusive_bit_mask	)	
```
I can set an exclusive mask to avoid matching up players in same role.
However, once a match has been made in a room, there is no feedback on what the merged bitmask looks like.

If Google Play Services would report back this merged mask, each peer would immediately know the opponent bitmasks right at the start of the match, which can be very valuable information.

**Comment by claywilkinson** [comment]
This is an interesting idea.  I am not sure which class would contain the accepted mask since the bits are only used during quickmatch matching.  Each mask provided from the caller is AND'ed, and the result must be 0 for the players to be matched up.  This means the combined mask for the room is always 0.  It's not an attribute of the participant, since named invitees don't use the quickmatch room builder, so the mask is null.

I think this type of configuration should be handled by the game.  For example, exchange this information once the player is connected to the room.

**Comment by stolk** [comment]
Good point: the combined mask returned would indeed not be the AND'ed one,
but maybe the OR'ed one?
That way the game will know immediately which other 'player roles' he's up
against without doing communication.
But yeah, invited matches without masks, this would make no sense.
So that would limit usefulness.


On Mon, Sep 14, 2015 at 9:13 AM, Clayton Wilkinson <notifications@github.com
> wrote:

> This is an interesting idea. I am not sure which class would contain the
> accepted mask since the bits are only used during quickmatch matching. Each
> mask provided from the caller is AND'ed, and the result must be 0 for the
> players to be matched up. This means the combined mask for the room is
> always 0. It's not an attribute of the participant, since named invitees
> don't use the quickmatch room builder, so the mask is null.
>
> I think this type of configuration should be handled by the game. For
> example, exchange this information once the player is connected to the room.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/playgameservices/android-basic-samples/issues/161#issuecomment-140128509>
> .
>



-- 

“Programming today is a race between software engineers striving to build
bigger and better idiot- proof programs, and the Universe trying to produce
bigger and better idiots. So far, the Universe is winning.” (R Cook).

**Comment by stolk** [comment]
May be less useful than I originally thought it would be. Closing.
