### ISSUE TITLE
Remove AppState dependencies from BaseGameUtils java classes

### ISSUE THREAD

**Issue by kiranb47** [playgameservices/android-basic-samples#164]
As AppState is depricated, i think it dependencies can be removed from BaseGameUtils library!

**Comment by claywilkinson** [comment]
Thanks for the comment. If you'd like, feel free to submit a pull request with the update.

**Comment by erahal** [comment]
Hello, not only the dependency should be removed, the project now does not compile since their is an import in the GamerHelper.Java class ( line 13) for the appstate (import com.google.android.gms.appstate.AppStateManager;) and it is used later on in the class ( 2 instances ), thus the class also needs to be updated in order for the project to compile.

I use android studio and I have set the playservices with a '+' instead of version to always use the latest, visiting an old project to update. It didn't compile with the latest play services version.

**Comment by edesdan** [comment]
Hello, I'm having the same issue after updating the play-services to 8.1 version.
