### ISSUE TITLE
CPU spinning problem with google play services 9.2.56

### ISSUE THREAD

**Issue by nixomose** [playgameservices/android-basic-samples#209]
I don't know where else to report this, but I have to do something.

It would seem the 9.2.56 update to google play services causes a spinning cpu problem, kills my phone in a few hours.

I have an "034" series machine. Samsung captivate glide running stock android 4.0.4

Since that update went in, my cpu spins all the time and there's nothing I can do.
As soon as I install an older version of the apk from apkmirror, it gets replaced with the new one and I'm back to square one.

It makes the phone unusably slow until the battery died.

I can't find anywhere to report a problem like this, and it happened to some of my other phones I do development with as well.

Is there a place to report bugs like this?
Please? help? I need my phone to work.

**Comment by davidbessire** [comment]
i also have this problem.  Noticed it first last Thursday that battery was draining much faster than before.  Google Play Services seems to continuously spawn processes / services which quickly die and are then replaced.  Tablet is noticably hot to the touch.  With tablet in idle mode, tablet is drained from full charge to 0 in a few hours.

Rebooted tablet in Safe Mode; Google Play Services did not start and battery life was normal.

Please note also this post in AOSP bug tracker about the same issue:

http://code.google.com/p/android/issues/detail?id=214975

i hope this is the right place to discuss this, because as of now this update has basically destroyed a tablet that i've been quite happy with for the prior 5 years.

**Comment by mwgray** [comment]
I'm afraid this isn't the right place for this bug.  This repo is only for the Google Play Games java samples.   If you are still encountering this issue you can try https://support.google.com.
