### ISSUE TITLE
UNREGISTERED_ON_API_CONSOLE

### ISSUE THREAD

**Issue by techyon7** [playgameservices/android-basic-samples#248]
I have just added my first app on the Developer Console and set up Play services for it, now this issue has been eating my brain up for like 2 whole days. I have added two testers(including me) and released it in alpha. I have linked my apps using correct SHA-1 key but it shows "Failed to sign in" when trying to connect to Play Services and log shows UNREGISTERED_ON_API_CONSOLE. What could be wrong? I have linked the correct SHA-1 key that I used to sign the apk with.
My logcat: https://pastebin.com/Mzwd04VR
One more thing that when I tried the apk separately(not from play store), I am able to connect to Play Services but from the alpha testing play store site, I can't.
Any Help?﻿

**Comment by claywilkinson** [comment]
The error UNREGISTERED_ON_API_CONSOLE definitely points to a configuration issue related to the package id, the SHA1 and the game app ID.

Since you can sign in when you run locally and not from the one in the play store, one thing to be aware of is which key you are signing the APK with.  Could it be that you are using a debug keystore to sign it locally and the one on the Play Store is signed with a release key (which will have a different SHA1) ?

**Comment by a159nish** [comment]
I thoroughly checked my code line by line and was able to resolve it. Thank You and sorry for the late reply.
